agent:
    serverurl: http://localhost:8081/uino/
    localserver:
        basepath: /uino
        bindaddr: 0.0.0.0:8081
        enable: false
        autostart: true
    systemsettings:
        restarttaskcron: '*/1 * * * *'
    enablerestarttask: true
