agent:
    serverurl: ""
    localserver:
        basepath: /uino
        bindaddr: localhost:8081
        enable: false
        autostart: true
    systemsettings:
        restarttaskcron: '*/1 * * * *'
    enablerestarttask: false
