agent:
    serverurl: ""
    localserver:
        basepath: /uino
        bindaddr: 0.0.0.0:8081
        enable: false
        autostart: false
    systemsettings:
        restarttaskcron: '*/1 * * * *'
    enablerestarttask: false
