// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectExePath(arg1:string):Promise<string>;

export function ServerShutdown():Promise<void>;

export function ServerStart(arg1:string,arg2:string):Promise<void>;

export function UnrealStart(arg1:string,arg2:Array<string>):Promise<number>;

export function UnrealStop(arg1:number):Promise<void>;
